name: 'Use RFC Service'
author: 'Nikita Matsnev'
description: 'Create and close fast RFC in GHA'

branding:
  icon: 'file'
  color: 'yellow'
inputs:
  Email:
    description: 'Your e-mail'
    required: true
  AssignmentGroup:
    description: 'e.g. RFC2365314'
    required: true
  ApplicationName:
    description: 'e.g. devportal'
    required: true
  EscalatedBy:
    description: 'e.g. name.surname@dhl.com'
    required: true
  ChangeCoordinator:
    description: 'e.g. name.surname@dhl.com'
    required: true
  Title:
    description: 'Title'
    required: true
  Description:
    description: 'Description'
    required: true
  Approver:
    description: 'gsn_template@dhl.com'
    required: true
  Template:
    description: 'RFC1234567'
    required: true
  Username:
    description: 'Your username for authentication'
    required: true
    type: string
  Password:
    description: 'Your password for authentication'
    required: true
    type: string
  Environment:
    description: 'Deployment environment'
    required: true
    type: string
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '"${{ inputs.Email }}"'
    - '"${{ inputs.AssignmentGroup }}"'
    - '"${{ inputs.ApplicationName }}"'
    - '"${{ inputs.EscalatedBy }}"'
    - '"${{ inputs.ChangeCoordinator }}"'
    - '"${{ inputs.Title }}"'
    - '"${{ inputs.Description }}"'
    - '"${{ inputs.Approver }}"'
    - '"${{ inputs.Template }}"'
    - '"${{ inputs.Username }}"'
    - '"${{ inputs.Password }}"'
    - '"${{ inputs.Environment }}"'
